name: vvs_autenticacao
description: Package usado para autenticação nos projetos em Flutter da VVS Sistemas
version: 1.2.2

homepage: https://github.com/bernardoveras/vvs_autenticacao/vvs_autenticacao.dart

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  vvs_core: ^1.3.0
  equatable: ^2.0.5
  dio: ^4.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  test:
  flutter_lints: ^1.0.0
  mocktail: ^0.3.0

flutter: